package technical.assessment.convert_tickets_booking.booking.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import technical.assessment.convert_tickets_booking.booking.dto.BookingRequestDto;
import technical.assessment.convert_tickets_booking.booking.model.Booking;
import technical.assessment.convert_tickets_booking.booking.model.BookingStatus;

import java.util.List;

public interface BookingService {
    
    /**
     * Creates a new booking with the following process:
     * 1. Iterates through booking items and reduces ticket quantities atomically in the database.
     * 2. Validates that tickets are not sold out (throws RuntimeException if insufficient).
     * 3. Persists the booking and its items within a single transaction.
     * 4. Triggers an asynchronous operation log entry.
     *
     * @param request The booking request DTO.
     * @return The saved Booking entity.
     */
    Booking createBooking(BookingRequestDto request);

    /**
     * Retrieves a booking by its unique ID.
     * Throws RuntimeException if the booking is not found.
     *
     * @param id The ID of the booking.
     * @return The found Booking entity.
     */
    Booking getBookingById(Integer id);

    /**
     * Retrieves all bookings associated with a specific user.
     *
     * @param userId The ID of the user.
     * @return A list of bookings for the user.
     */
    Page<Booking> getBookingsByUserId(Integer userId, Pageable pageable);

    /**
     * Updates the status of an existing booking and records the change in operation logs asynchronously.
     *
     * @param id The ID of the booking to update.
     * @param status The new status to apply.
     * @return The updated Booking entity.
     */
    Booking updateBookingStatus(Integer id, BookingStatus status);

    /**
     * Retrieves a booking by its unique idempotency key. 
     * Used to implement retry safety and prevent duplicate transactions.
     *
     * @param idempotencyKey The unique key generated by the client.
     * @return The found Booking or null if not exists.
     */
    Booking getByIdempotencyKey(String idempotencyKey);
}
